services:
  backend:
    restart: always
    container_name: unvail-backend
    build: ./backend
    env_file:
      - .env.production
    expose:
      - "8080"
    networks:
      - global_network

  frontend:
    restart: always
    container_name: unvail-frontend
    build: ./frontend
    env_file:
      - .env.production
    environment:
      - PORT=5173
    expose:
      - "5173"
    networks:
      - global_network



networks:
  global_network:
    external: true
    name: global_network
