spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:gwon-db}:${DB_PORT:3306}/${DB_NAME:unvail}?serverTimezone=Asia/Seoul
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # 자바 코드를 짜면 DB 테이블이 자동으로 생김
    show-sql: true # 실행되는 SQL을 콘솔창에 보여줌
    properties:
      hibernate:
        format_sql: true

app:
  google:
    client-id: ${GOOGLE_CLIENT_ID:392628599507-md93s85gite0hnohg13ke18jnftes003.apps.googleusercontent.com}
  gemini:
    api-key: ${GEMINI_API_KEY:}
  admin:
    emails: ${ADMIN_EMAILS:}